# SPEC 08 — Mobile Companion App Integration

**Architecture reference:** `APP_BLUEPRINT.md` Section 1 (Mobile: React Native / Expo SDK 57)
**Files:** `mobile/app/`, `backend_fastapi/app/api/routers/mobile_route.py`

## Part 1 — Expo Setup & Networking
1. The mobile app resides strictly in the `mobile/` directory using Expo Router (SDK 57).
2. Because the main backend is a local FastAPI sidecar running on a desktop, the mobile app must scan a QR code generated by the desktop app (`app/dashboard/settings/page.tsx`) to discover the local LAN IP address and authentication token.
3. Implement `stores/connectionStore.ts` in the mobile app to persist the `desktop_ip` and `auth_token`.

## Part 2 — Mobile Feature Scope
The mobile app is NOT a full administrative suite. It is restricted to three operational roles:
1. **Inventory Scanner:** 
   - Use `expo-camera` to scan physical barcodes.
   - Display current stock levels, price, and expiration date.
   - Allow quick stock adjustments (calls `POST /api/v1/inventory/adjust`).
2. **Rx Queue Viewer:**
   - Read-only view of `stores/rxQueueStore.ts` data to notify pharmacy staff moving around the store when a prescription is ready.
3. **Analytics Dashboard (Owner Only):**
   - View top-selling items and daily revenue summary.

## Part 3 — Security & API Alignment
1. The mobile API calls must reuse the exact same `types/contracts.ts` definitions as the web dashboard. Copy the contracts file via a pre-build script into the mobile directory to guarantee type parity.
2. The FastAPI backend must configure CORS in `main.py` to allow requests from the local subnet (e.g., `192.168.1.0/24`) to accept requests from the mobile device.