"""
deploy_to_server.py — Deploy server_app.py + .env + HTML pages to PythonAnywhere.

Reads credentials from archive/.env:
    PYTHONANYWHERE_USERNAME
    PYTHONANYWHERE_API_TOKEN

Uploads:
    1. archive/server_app.py      -> /home/{username}/server_app.py
    2. archive/.env (secrets)      -> /home/{username}/.env
    3. archive/landing/index.html  -> /home/{username}/landing/index.html
    4. archive/admin/index.html    -> /home/{username}/admin/index.html
    5. archive/customer/index.html -> /home/{username}/customer/index.html

Then triggers a webapp reload so python-dotenv loads the new secrets.

Usage:
    python deploy_to_server.py              # upload all + reload
    python deploy_to_server.py --upload     # upload only
    python deploy_to_server.py --reload     # reload only
    python deploy_to_server.py --dry-run    # show what would happen
"""
import argparse
import os
import sys
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:
    print("[ERROR] python-dotenv required: pip install python-dotenv", file=sys.stderr)
    sys.exit(1)

try:
    import requests
except ImportError:
    print("[ERROR] requests required: pip install requests", file=sys.stderr)
    sys.exit(1)

# ── Load local .env ────────────────────────────────────────────────────
ENV_PATH = Path(__file__).resolve().parent / ".env"
load_dotenv(ENV_PATH)

USERNAME = os.environ.get("PYTHONANYWHERE_USERNAME", "")
API_TOKEN = os.environ.get("PYTHONANYWHERE_API_TOKEN", "")

API_BASE = "https://www.pythonanywhere.com/api"
DOMAIN = f"{USERNAME}.pythonanywhere.com"

# ── File paths ─────────────────────────────────────────────────────────
LOCAL_SERVER = Path(__file__).resolve().parent / "server_app.py"
REMOTE_SERVER = f"/home/{USERNAME}/server_app.py"

LOCAL_ENV = ENV_PATH
REMOTE_ENV = f"/home/{USERNAME}/.env"

# ── Secrets to upload (never include PYTHONANYWHERE credentials) ───────
_ENV_KEYS_TO_UPLOAD = [
    # Core
    "SERVER_ADMIN_SECRET",
    "PORTAL_SECRET",
    # Payment gateway (Paddle only)
    "PADDLE_API_KEY",
    "PADDLE_CLIENT_TOKEN",
    "PADDLE_PRICE_ID",
    "PADDLE_WEBHOOK_SECRET",
    # Webhook test mode (MUST be 0 in production)
    "WEBHOOK_TEST_MODE",
    # SMTP
    "SMTP_HOST",
    "SMTP_PORT",
    "SMTP_USER",
    "SMTP_PASSWORD",
    "SENDER_EMAIL",
    # Download URL
    "DOWNLOAD_URL",
    # Alerts
    "ALERT_WEBHOOK_URL",
    # Sentry
    "SENTRY_DSN",
    # Cron
    "CRON_SECRET",
    # GitHub (Crash Reporter)
    "GITHUB_TOKEN",
    "GITHUB_REPO",
]

# ── Static HTML pages to upload ────────────────────────────────────────
# server_app.py uses _ARCHIVE_DIR = os.path.dirname(os.path.abspath(__file__))
# which resolves to /home/{username}/ on PythonAnywhere.
# HTML pages must be uploaded to match: /home/{username}/{landing,admin,customer}/
_HTML_PAGES = [
    ("archive/landing/index.html",  "landing/index.html"),
    ("archive/landing/terms.html",  "landing/terms.html"),
    ("archive/landing/privacy.html", "landing/privacy.html"),
    ("archive/landing/refund.html", "landing/refund.html"),
    ("archive/admin/index.html",    "admin/index.html"),
    ("archive/customer/index.html", "customer/index.html"),
]


def _headers() -> dict:
    return {"Authorization": f"Token {API_TOKEN}"}


def _build_env_content() -> str:
    """Read the local .env and return only the server-facing secrets."""
    lines = []
    lines.append(f"# Auto-generated by deploy_to_server.py — do not edit manually")
    lines.append(f"# Deployed from: {LOCAL_ENV}")
    lines.append("")

    # Load all keys from the local .env
    local_env = {}
    if LOCAL_ENV.is_file():
        for raw_line in LOCAL_ENV.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, val = line.partition("=")
                local_env[key.strip()] = val.strip()

    for key in _ENV_KEYS_TO_UPLOAD:
        value = os.environ.get(key, local_env.get(key, ""))
        if value:
            lines.append(f"{key}={value}")
        else:
            lines.append(f"{key}=")

    # Safety: warn if WEBHOOK_TEST_MODE is not 0
    webhook_test = local_env.get("WEBHOOK_TEST_MODE", os.environ.get("WEBHOOK_TEST_MODE", "0"))
    if webhook_test != "0":
        print(f"[WARNING] WEBHOOK_TEST_MODE is '{webhook_test}' — forcing to '0' for production")
        # Overwrite the line we just wrote
        lines = [l for l in lines if not l.startswith("WEBHOOK_TEST_MODE=")]
        lines.append("WEBHOOK_TEST_MODE=0")

    lines.append("")
    return "\n".join(lines)


def _upload_file(remote_path: str, content: bytes, label: str, dry_run: bool, timeout: int = 30) -> bool:
    """Upload a single file to PythonAnywhere via the REST API."""
    if not USERNAME or not API_TOKEN:
        print(f"[ERROR] PYTHONANYWHERE_USERNAME or PYTHONANYWHERE_API_TOKEN not set")
        return False

    url = f"{API_BASE}/v0/user/{USERNAME}/files/path{remote_path}"

    print(f"[UPLOAD] {label}")
    print(f"[UPLOAD]   -> {remote_path}")
    print(f"[UPLOAD]   Size: {len(content)} bytes")

    if dry_run:
        print("[DRY-RUN] Would POST to:", url)
        return True

    try:
        resp = requests.post(
            url,
            headers=_headers(),
            files={"content": (remote_path.split("/")[-1], content, "text/plain")},
            timeout=timeout,
        )
        if resp.status_code in (200, 201):
            action = "updated" if resp.status_code == 200 else "created"
            print(f"[UPLOAD] Success — {label} {action}")
            return True
        else:
            print(f"[UPLOAD] Failed — HTTP {resp.status_code}: {resp.text[:300]}")
            return False
    except requests.exceptions.RequestException as exc:
        print(f"[UPLOAD] Network error: {exc}")
        return False


def upload_server(dry_run: bool = False) -> bool:
    """Upload server_app.py."""
    if not LOCAL_SERVER.is_file():
        print(f"[ERROR] Local file not found: {LOCAL_SERVER}")
        return False
    return _upload_file(REMOTE_SERVER, LOCAL_SERVER.read_bytes(), "server_app.py", dry_run)


def upload_env(dry_run: bool = False) -> bool:
    """Upload a sanitized .env containing only server-facing secrets."""
    content = _build_env_content().encode("utf-8")
    return _upload_file(REMOTE_ENV, content, ".env (secrets)", dry_run)


def upload_html_pages(dry_run: bool = False) -> bool:
    """Upload static HTML pages (landing, admin, customer portal)."""
    ok = True
    # Script lives in archive/, so parent goes up to project root
    project_root = Path(__file__).resolve().parent.parent
    for local_rel, remote_rel in _HTML_PAGES:
        local_path = project_root / local_rel
        remote_path = f"/home/{USERNAME}/{remote_rel}"
        if not local_path.is_file():
            print(f"[WARNING] HTML page not found, skipping: {local_path}")
            continue
        ok = _upload_file(remote_path, local_path.read_bytes(), f"HTML: {remote_rel}", dry_run) and ok
    return ok


def upload_downloads(dry_run: bool = False) -> bool:
    """Upload the downloads/ directory (pharmacy-hwid.exe) to PythonAnywhere."""
    downloads_dir = Path(__file__).resolve().parent / "downloads"
    if not downloads_dir.is_dir():
        print(f"[WARNING] downloads/ directory not found, skipping: {downloads_dir}")
        return True

    ok = True
    for exe_file in downloads_dir.glob("*.exe"):
        remote_path = f"/home/{USERNAME}/downloads/{exe_file.name}"
        print(f"[UPLOAD] Binary: {exe_file.name} ({exe_file.stat().st_size:,} bytes)")
        ok = _upload_file(remote_path, exe_file.read_bytes(), f"Binary: {exe_file.name}", dry_run, timeout=180) and ok
    return ok


def reload_webapp(dry_run: bool = False) -> bool:
    """Trigger a webapp reload on PythonAnywhere."""
    if not USERNAME or not API_TOKEN:
        print("[ERROR] PYTHONANYWHERE_USERNAME or PYTHONANYWHERE_API_TOKEN not set")
        return False

    url = f"{API_BASE}/v0/user/{USERNAME}/webapps/{DOMAIN}/reload/"

    print(f"[RELOAD] Triggering reload for {DOMAIN}")

    if dry_run:
        print("[DRY-RUN] Would POST to:", url)
        return True

    try:
        resp = requests.post(url, headers=_headers(), timeout=30)
        if resp.status_code == 200:
            print("[RELOAD] Success — webapp reloaded")
            return True
        else:
            print(f"[RELOAD] Failed — HTTP {resp.status_code}: {resp.text[:300]}")
            return False
    except requests.exceptions.RequestException as exc:
        print(f"[RELOAD] Network error: {exc}")
        return False


def main():
    parser = argparse.ArgumentParser(description="Deploy server_app.py + .env to PythonAnywhere")
    parser.add_argument("--upload", action="store_true", help="Upload only (no reload)")
    parser.add_argument("--reload", action="store_true", help="Reload only (no upload)")
    parser.add_argument("--dry-run", action="store_true", help="Show what would happen without making changes")
    args = parser.parse_args()

    do_upload = not args.reload
    do_reload = not args.upload

    print("=" * 56)
    print("  PythonAnywhere Deployment")
    print("=" * 56)
    print(f"  User    : {USERNAME or '(not set)'}")
    print(f"  Domain  : {DOMAIN}")
    print(f"  Server  : {LOCAL_SERVER}")
    print(f"  Secrets : {', '.join(_ENV_KEYS_TO_UPLOAD)}")
    print(f"  HTML    : {len(_HTML_PAGES)} pages (landing, admin, portal)")
    print("=" * 56)

    ok = True

    if do_upload:
        ok = upload_server(dry_run=args.dry_run) and ok
        ok = upload_env(dry_run=args.dry_run) and ok
        ok = upload_html_pages(dry_run=args.dry_run) and ok
        ok = upload_downloads(dry_run=args.dry_run) and ok

    if do_reload and ok:
        ok = reload_webapp(dry_run=args.dry_run) and ok

    print()
    if ok:
        print("[DONE] Deployment completed successfully.")
    else:
        print("[DONE] Deployment finished with errors — see above.")
        sys.exit(1)


if __name__ == "__main__":
    main()
